name:                haskell
version:             0.1.0.0
license:             BSD3
author:              "Rafael S. Calsaverini"
maintainer:          "example@example.com"
copyright:           "2019 Rafael S. Calsaverini"

description:         Boehm-Berarucci encodings examples.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell
    - QuickCheck
    - hspec
    - hspec-discover
